api:
    insecure: true
    dashboard: true
    debug: true
  
entryPoints:
    http:
        address: ":9001"
    web:
        address: ":9002"
 
log:
    level: DEBUG
    filePath: ./traefik.log
    format: json
               

providers:
    # Enable the file provider to define routers / middlewares / services in file
    file:
        filename: ./config-dev-cloud-api.toml
  
